MAX_FAILED_ATTEMPTS = 2

MAX_UNKNOWN_INTENTS = 2

HANDOFF_REASON_USER_REQUEST = "USER_REQUEST"

HANDOFF_REASON_REPEATED_FAILURE = (
    "REPEATED_FAILURE"
)

HANDOFF_REASON_UNKNOWN_INTENT = (
    "UNKNOWN_INTENT"
)